### ISSUE TITLE
Error: Cannot find module '../login'

### ISSUE THREAD

**Issue by voronianski** [TooTallNate/node-spotify-web#100]
There is no such file in project - https://github.com/TooTallNate/node-spotify-web/blob/master/example/play.js#L9

```bash
MacBook-Pro-Dmitri:example dmitri$ node play.js

module.js:340
    throw err;
          ^
Error: Cannot find module '../login'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/dmitri/github/node-spotify-web/example/play.js:9:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by TooTallNate** [comment]
Ya, you gotta make it yourself.
It must have `username` and `password` string properties exported.

**Comment by voronianski** [comment]
@TooTallNate yep, thanks!
