### ISSUE TITLE
Login not working (again)

### ISSUE THREAD

**Issue by giacecco** [TooTallNate/node-spotify-web#103]
Hi All, the Spotify people must have changed something again, some time in the last three weeks. [It's happening to @Watiswat, too](https://github.com/TooTallNate/node-spotify-web/issues/87#issuecomment-69407082). The code I am using is basic and worked perfectly at the beginning of December '14.

```
Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
```

**Comment by giacecco** [comment]
Closed as duplicate of https://github.com/TooTallNate/node-spotify-web/issues/102 .
