### ISSUE TITLE
Protobuf issue...

### ISSUE THREAD

**Issue by psychosteve** [TooTallNate/node-spotify-web#106]
Hi having trouble exporting tracks. Tried the metadata.proto fix by yodiz but with no luck! :(

Here's the error I'm having...

<pre><code>Error: Illegal value for Message.Field .spotify.metadata.proto.AudioFile.format: 8 (not a valid enum value)
    at ProtoBuf.Reflect.Field.verifyValue (/Users/Lloyd/Desktop/spotydl/node_modules.darwin.x64/spotify-web/node_modules/protobufjs/ProtoBuf.js:2318:27)
    at Message.set (/Users/Lloyd/Desktop/spotydl/node_modules.darwin.x64/spotify-web/node_modules/protobufjs/ProtoBuf.js:1710:50)
    at ProtoBuf.Reflect.Message.decode (/Users/Lloyd/Desktop/spotydl/node_modules.darwin.x64/spotify-web/node_modules/protobufjs/ProtoBuf.js:2136:29)
    at ProtoBuf.Reflect.Field.decode (/Users/Lloyd/Desktop/spotydl/node_modules.darwin.x64/spotify-web/node_modules/protobufjs/ProtoBuf.js:2591:46)
    at ProtoBuf.Reflect.Message.decode (/Users/Lloyd/Desktop/spotydl/node_modules.darwin.x64/spotify-web/node_modules/protobufjs/ProtoBuf.js:2134:51)
    at Message.decode (/Users/Lloyd/Desktop/spotydl/node_modules.darwin.x64/spotify-web/node_modules/protobufjs/ProtoBuf.js:1979:41)
    at Function.protobufjs_parse_wrapper (/Users/Lloyd/Desktop/spotydl/node_modules.darwin.x64/spotify-web/lib/schemas.js:98:39)
    at Spotify._parse (/Users/Lloyd/Desktop/spotydl/node_modules.darwin.x64/spotify-web/lib/spotify.js:1287:20)
    at parseData (/Users/Lloyd/Desktop/spotydl/node_modules.darwin.x64/spotify-web/lib/spotify.js:591:18)
    at Spotify.<anonymous> (/Users/Lloyd/Desktop/spotydl/node_modules.darwin.x64/spotify-web/lib/spotify.js:651:16)
</pre></code>

**Comment by felixhammerl** [comment]
yes, apparently spotify introduced a new file format. @TooTallNate this could probably be solved by #77 ? The workaround from #75 where he added dummy values to the protobuf schema no longer works. if i add a dummy value to the protocol buffer schema, it tells me that the track is not playable in my locale. can someone confirm?

**Comment by Kh4l3tH** [comment]
[i already confirmed :)](https://github.com/TooTallNate/node-spotify-web/issues/75#issuecomment-74551995)

**Comment by vincentcox** [comment]
any updates?

**Comment by R4wizard** [comment]
I am also experiancing this issue.

**Comment by samsnyder** [comment]
I've started to get AudioFile values of 10 and 11 aswell.
