### ISSUE TITLE
dreaded error code 6

### ISSUE THREAD

**Issue by nyboer** [TooTallNate/node-spotify-web#128]
I've tried this on 3 different computers, 3 different OS'es (OS X, Ubuntu, and Debian on an ARM7 SOC), and I'm consistently getting 

```
Playing: Kraftwerk - Tour De France - 2009 Remastered Version

events.js:154
      throw er; // Unhandled 'error' event
      ^
TrackError: Failed to send to backend
    at Spotify._onmessage (/Users/nbor/Documents/progproj/node/node-spotify-web/lib/spotify.js:464:15)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
```

if I just console.log(msg) at line 464 in spotify.js, it returns

```
{ error: [ 12, 1, '' ], id: 6 }
```

Error 6 seems to be a common problem with Windows machines, according to the Spotify community boards. I found one [thing](http://stackoverflow.com/questions/32729395/spotify-sdk-loginwithsession-causes-error-code-6) that documents it as  "A playback function was invoked before playback was initalized properly."

I'm kind of at a loss. It worked last week... :(

**Comment by jeffdran** [comment]
Still having this issue? I can look into it via VM if so.

**Comment by MadScripter** [comment]
Having the same issue.

**Comment by jeffdran** [comment]
Have you tried updating anything? I'm using the fork from Xstasy and running protobufjs 2.2.1, no issues on Win. Loading my VM now to test things with your architecture.

**Comment by MadScripter** [comment]
I've tried updating, I just now tried the fork from "Xstasy" and I am now getting:
"Uncaught Exception:
TypeError: Cannot read property 'length' of undefined
at Object.exports.hex2bin"
Something to do with encryptions

This happens when using the "trackUri" method.

**Comment by jeffdran** [comment]
Finally got a bit of free time and managed to get things working with OS X. Simply ran npm install on the new package.json for Xstasy's fork, then npm update. Running any version of node before 4.4.0 has worked so far. My spotify.js has only a few minor tweaks different than Xstasy's, but nothing substantial.

**Comment by MadScripter** [comment]
I have tried all of the above and I'm still getting the previously mentionned error, it happens when using the following methods on a track Instance: trackUri, play and getStreamURL.

Also, I am under Windows.

**Comment by jeffdran** [comment]
Ok, so trackUri is giving me undefined, strangely play works, and getStreamURL gives me a callback error. I'll see if I can fix this. trackUri seems easy, but I'm not entirely sure why getStreamURL is giving me a callback error. Method looks underdeveloped though.

I assumed everything else worked because play worked fine for my app, but I do have my own URI method.

**Comment by ghost** [comment]
getStreamURL is something I added back before Spotify added encrypted streams - it's no longer functional and should really be removed.

**Comment by MadScripter** [comment]
I figured it out. Since I'm using electron, the newer versions come with node 6.*, I had to downgrade back to electron v1.0.2 for the library to work correctly.
It's still annoying having to log-in everytime you want to play a track though, but oh well..
Thanks for the help guys!

**Comment by jeffdran** [comment]
@MadScripter You can disable that. I never had it setup that way with my app, but I see others with that. Just look for spotify.disconnect (or whatever the object name is), and remove.

**Comment by MadScripter** [comment]
If you are talking about the "example" then I never used it either, but if I try and play 2 songs in a row, I get an error about the account not being premium, so I assume you have a premium account :P

**Comment by jeffdran** [comment]
I plead the 5th. You can bypass such a requirement though. It's seriously just a simple check.

**Comment by MadScripter** [comment]
Haha alright I'll try to figure it out, thanks!

**Comment by jeffdran** [comment]
Such a modification would go against the TOS of course, and also probably yield some errors once in a while. One would probably have to add some error handling to gracefully recover from such errors.
