### ISSUE TITLE
TypeError: Cannot read property 'csrftoken' of undefined

### ISSUE THREAD

**Issue by LinusU** [TooTallNate/node-spotify-web#52]
Seems related to #51, this one also just happened one time. It would be nice if we could catch both and either return the `err` to the login callback, or just try again.

I will try to whip up a pull request if I have time.

``` text
TypeError: Cannot read property 'csrftoken' of undefined
    at Spotify._onsecret (node_modules/spotify-web/lib/spotify.js:265:54)
    at Request.callback (node_modules/spotify-web/node_modules/superagent/lib/node/index.js:584:30)
    at Request.<anonymous> (node_modules/spotify-web/node_modules/superagent/lib/node/index.js:133:10)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (node_modules/spotify-web/node_modules/superagent/lib/node/index.js:714:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by Shigawire** [comment]
Hey, tracked that down to the _onsecret method.

``` javascript
Spotify.prototype._onsecret = function (err, res) {
  if (err) return this.emit('error', err);
  if(res.error) return this.emit('error', res.error);
```

will at least fail more gracefully than throwing. For me, it returns a 504 - Gateway timeout.
