### ISSUE TITLE
 Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue

### ISSUE THREAD

**Issue by hanxue** [TooTallNate/node-spotify-web#75]
After successfully logging in, I get this error in `spotify.get()`. Full error message

```
Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)
    at ProtoBuf.Reflect.Field.verifyValue (/usr/local/lib/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2321:27)
    at Message.add (/usr/local/lib/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1693:53)
    at ProtoBuf.Reflect.Message.decode (/usr/local/lib/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2137:29)
    at ProtoBuf.Reflect.Field.decode (/usr/local/lib/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2594:46)
    at ProtoBuf.Reflect.Message.decode (/usr/local/lib/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2137:51)
    at Message.decode (/usr/local/lib/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1982:41)
    at Function.protobufjs_parse_wrapper [as parse] (/usr/local/lib/node_modules/spotify-web/lib/schemas.js:98:39)
    at Spotify._parse (/usr/local/lib/node_modules/spotify-web/lib/spotify.js:1251:20)
```

**Comment by Kh4l3tH** [comment]
For me this workaround didnt work. a new error appeared stating that the track is not playable in my country (which was not true).
however, i found that the x64 version of 0.10 branch of nodejs didnt throw the error at all. (all later versions failed for me as did all x86 versions)
http://nodejs.org/dist/v0.10.36/x64/
with this version i got spotify-web to run with old node-modules. with the newest ones the error reappeared so i stick with using the old ones.
hope this helps somebody...

**Comment by vincentcox** [comment]
nope didn't worked for me :(

**Comment by gp-slick-coder** [comment]
didn't worked for me too :(

**Comment by HendrikRoth** [comment]
Same issue on osx.

**Comment by R4wizard** [comment]
I am also experiancing this issue. Both on windows and centos 6.

I have attempted the workaround above (on linux because i couldn't get the protobuf compiler thing to work), and had the same results noted above (track not available in my country).

**Comment by jotadepicas** [comment]
Same issue here running on raspberry pi, raspbian wheezy. Nodejs version 4.3.2.
