### ISSUE TITLE
Track is not playable in country

### ISSUE THREAD

**Issue by timolins** [TooTallNate/node-spotify-web#90]
If a try to play a track (no matter which track it is), I receive the following error: 

```
Error: Track is not playable in country "AT"
    at eval (../../../node_modules/spotify-web/lib/spotify.js:1041:8)
    at process._tickCallback (node.js:534:11)
```

I'm using nodewebkit ("classic" NodeJS worked just fine). And yes, the song is playable in my country (Tried the tracks with Desktop Client & Web Client).

**Comment by liam-middlebrook** [comment]
Have there been any updates on whether or not this would work?

**Comment by liam-middlebrook** [comment]
I've tracked the bug down to `spotify.js` line 960. It's using the `has` function to compare an integer from `restriction.catalogue` to a string from `type` which is deriving from line 959.

**Comment by dralletje** [comment]
I think this has to do with the difference between protobuf and protobufjs, when I try to play a track without protobuf installed it always gives this error, with protobuf installed it doesn't. Node-webkit might not be able to use native modules?

**Comment by antxxxx** [comment]
@dralletje i noticed a small issue in your fix in that it kept trying to map undefined values. I have created https://github.com/TooTallNate/node-spotify-web/pull/110 which has a fix that works for me

**Comment by sciencepro** [comment]
@TooTallNate @antxxxx 

FYI, this last fix actually broke the functionality on my machine.  Rolling back fixes it.

**Comment by juanmito** [comment]
@antxxxx I've tried your fix, and didn't work for me. :(

**Comment by arnav-gudibande** [comment]
just replace this function in lib/spotify.js with this:
(this is just a quick and dirty fix)

Spotify.prototype.recurseAlternatives = function (track, country, fn) {
  debug('recurseAlternatives()');
  function done () {
    process.nextTick(function () {
      fn(null, track);
    });
  }
  done();
};

this bypasses the buggy "check country" code
